prometheus:
  prometheusSpec:
    resources:
      requests:
        memory: 250Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 1000m
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 50Gi
    enableRemoteWriteReceiver: true
    additionalArgs:
      - name: web.enable-otlp-receiver
        value: ''
    remoteWrite: 
      - url: "http://prometheus-kube-prometheus-prometheus.obs:9090/api/v1/write"
        # basicAuth:
        #   username: "admin"
        #   password: "admin"
        # writeRelabelConfigs:
        #   - sourceLabels: [__name__]
        #     targetLabel: job
