prometheus:
  prometheusSpec:
    resources:
      requests:
        memory: 250Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 1000m
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 50Gi