apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry
  namespace: default
data:
  OTEL_SERVICE_NAME: api
  OTEL_EXPORTER_OTLP_ENDPOINT: http://my-opentelemetry-collector.obs.svc.cluster.local:4317
  OTEL_EXPORTER_OTLP_INSECURE: 'true'
  OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: 'true'
  OTEL_TRACES_EXPORTER: otlp
  OTEL_METRICS_EXPORTER: otlp
  OTEL_LOGS_EXPORTER: otlp