config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318



  exporters:
    # Exporter que imprime os dados de traces/metrics no log em modo debug


    # Exporter que envia os traces para o Tempo
    otlp:
      endpoint: http://tempo.obs.svc.cluster.local:4317
      tls:
        insecure: true

  service:
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [batch]
   

      traces:
        receivers: [otlp]
        exporters: [otlp]  # envia para o Tempo e loga no console
